### ISSUE TITLE
Query module: automatically import multi-layer gpkgs from the layer switcher

### ISSUE THREAD

**Issue by JowieXiang** [citysciencelab/open-city-toolkit#117]
The error below happens when query module tries to import all layer switcher layers into GRASS. This happens because v.import doesn't automatically import multi-layer gpkgs. Extra steps need to be taken to achieve multi-layer gpkg import...

failed to import /usr/share/geoserver/data_dir/data/latacunga/vulnerabilidad.gpkg due to error: Error: Command failed: grass "../grass/global/PERMANENT" --exec v.import input="/usr/share/geoserver/data_dir/data/latacunga/vulnerabilidad.gpkg" output="vulnerabilidad" --overwrite WARNING: Searched for a web browser, but none found Starting GRASS GIS... Executing <v.import input=/usr/share/geoserver/data_dir/data/latacunga/vulnerabilidad.gpkg output=vulnerabilidad --overwrite> ... WARNING: Projection of layer <VulnerabilidadLatacunga> is different from projection of layer <VulnerabilidadGPKG> ERROR: Detected different projections of input layers. Input layers must be imported separately. WARNING: Projection of layer <VulnerabilidadLatacunga> is different from projection of layer <VulnerabilidadGPKG> ERROR: Detected different projections of input layers. Input layers must be imported separately. ERROR: Unable to create location from OGR datasource </usr/share/geoserver/data_dir/data/latacunga/vulnerabilidad.gpkg> Execution of <v.import input=/usr/share/geoserver/data_dir/data/latacunga/vulnerabilidad.gpkg output=vulnerabilidad --overwrite> finished. Cleaning up default sqlite database ... Cleaning up temporary files...

**Comment by ArjamaM** [comment]
Cancelled.
