### ISSUE TITLE
Brush-up suggestions

### ISSUE THREAD

**Issue by JowieXiang** [citysciencelab/open-city-toolkit#158]
Jan and Jowie should come up with some brush up proposals.

**Comment by janbehrens** [comment]
Suggestion: revamp the display of results
- when an analysis completes, add a direct link to the PDF in the communications tab
- open each PDF in a new tab, not in an iframe within the modal
- in the result modal, give a proper overview of available PDFs, grouped by module and sorted by date (most recent first), using appropriate [Bootstrap compenents](https://getbootstrap.com/docs/3.4/components/) in the layout

**Comment by janbehrens** [comment]
Suggestion: movable left pane
- allow the left pane to use a variable width, depending on context, or adjustable by the user

**Comment by janbehrens** [comment]
converted to issues #171, #172
