### ISSUE TITLE
translate to spanish

### ISSUE THREAD

**Issue by LisaReudenbach** [citysciencelab/open-city-toolkit#41]

**Comment by natastro** [comment]
Happy to help with Spanish translations if needed! Thank you! 😄

**Comment by LisaReudenbach** [comment]
Hi Natalie! Thanks so much for your kind offer! We do have Spanish speaking partners in our project, who will take care of the translations, so no need for support. May I ask how you came across our project?

**Comment by natastro** [comment]
Thank you for the response @LisaReudenbach ! I usually search for i18n or Spanish as a keyword on Github issues to see if I can help anyone with Spanish translations and open-city-toolkit was on the first page 😄 

Take care!

**Comment by janbehrens** [comment]
What is the timeline for this?
