### ISSUE TITLE
Usability: Refine messages in communication box

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#50]
To make it clearer which button does what:  Confusion between module button, settings and layers button. Ideas: interactive manual, pop-up box, floating window, virtual tour.

**Comment by JowieXiang** [comment]
**Added a blink function** 300d77e9cad6f59c464f2027c40d6b4b9dcabc63: 
user can click on the UI components' names (for e.g. in a message), and the corresponding component will blink 3 times

**Comment by JowieXiang** [comment]
Added a blink effect to guide the user to the corresponding UI elements (settings / layer switcher)
6b6400e3708f844b9a38b0fdd9c8a94ad1f80df7

**Comment by JowieXiang** [comment]
To familiarize users with the UI, is would be helpful to display the user manual on the first visit
    Quick fix: display the manual every time the page is visited
   long-term solution: use cookies/user system to generate targeted behavior
