### ISSUE TITLE
Usability: Improvement of error messages

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#51]
Not clear when the module has to be re-run in order to start over, confusion regarding the fact that points/stricken area need to be chosen inside the selected area and scope of area.. Ideas: Short intro, message to mention points need to be chosen within area.

**Comment by JowieXiang** [comment]
Added instruction "points and polygons have to be in the selection area" in the messages. 
6b6400e3708f844b9a38b0fdd9c8a94ad1f80df7

**Comment by LisaReudenbach** [comment]
when an error message occurs, should add: 'please restart the module in case an error occurs'
