### ISSUE TITLE
Query module: When selecting 'choose layer to select from' it should give information on what kind of data you can query and the unit of this data.

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#55]
Currently 'show attributes' only opens the dataset mentioning some technical details describing columns, number of rows, etc. This probably wont make much sense to the user to understand what to query. Once the metadata is available, this part should be changed to make more sense to users.

**Comment by JowieXiang** [comment]
At the moment, available data are:
1. type - CHARACTRE/DOUBLE PRECISION/ INTEGER
2. description - needs to be added in the metadata.json
3. min/max value
The value's unit is not provided by default. If required, this data needs to be added manually to the metadata.json during data-preparation phase.

**Comment by ArjamaM** [comment]
After adding the data manually to the metadata.json, the information is clearer than before, but would still require information on the data from the user's side. Assuming this is a pre-requisite and hence closing this issue.
