### ISSUE TITLE
Query module: Logic is not clear, you set the selection as 'area of all analyses' and time map is calculated in the selection area, but for query, you have to define an area again. This is a double process.

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#56]
There should be an option: 'Keep this selection area' or 'choose a sub-selection area'.

**Comment by JowieXiang** [comment]
> There should be an option: 'Keep this selection area' or 'choose a sub-selection area'.

I've fixed this in this commit 940b0e9ca9668066675f0a1d3ebbaae4c949d16a 
Now the user can only use the selection area as the query area. I think it adds extra complexity if we allow them to choose whether to use the selection area or a sub-selection area. So I kept it simple. But we can discuss about it :)

**Comment by LisaReudenbach** [comment]
good! Better to keep it simple. If they want a different area, they can simply define a new 'selection area'.
