### ISSUE TITLE
Point chosen on the map is only visible when selection 'from point' is switched on in the layer switcher. Should be visible when 'drawings on the map' is switched on.

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#62]

**Comment by JowieXiang** [comment]
Added a fix in this commit 09bae33287912c28241ff4d1c4415ce18725a768.
Now when the use starts 'Calculate Time Map' module, the via/from/to points and the stricken area layers are automatically switched on in the map.
