### ISSUE TITLE
Add a short description in communication box when choosing module, add before clicking 'run'.

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#69]

**Comment by janbehrens** [comment]
What if the module option is changed while there are other contents in the dialog area?

**Comment by LisaReudenbach** [comment]
In the dropdown-menu there could be one item 'choose module' in addition to the different modules. when you choose that one, we show the descriptions in the communication box. When you choose a module directly there is no description. OR
Previous content in the communication box is cleared whenever you click on one of the modules in the drop-down-menu, and instead the module description is shown.

**Comment by janbehrens** [comment]
It is generally not a good idea to use a UI element for something that it is not intended for. In this case: to use the dialog box to display help in it. If you overwrite a dialog message with a help message, then what is the state of the dialog and the process running in its background? Is it cancelled? Can it be resumed from where it has been left off? All this is going to indroduce new pitfalls for inexperienced users.
Instead I'd suggest to add a help/info button next to the module switcher. If clicked, the help message would show up in a small, popup-like box right next to it.
