### ISSUE TITLE
Set average speed on the road needs improvement

### ISSUE THREAD

**Issue by LisaReudenbach** [citysciencelab/open-city-toolkit#73]
If you want to change the average road speed, it gives you the option to put a general % - but i think this option should be for cities where the average speed is different from the given values and you want to adapt it, e.g. because of road condtion or cultural habits. Therefore you need the option to change average speed on all road types to a different average - instead of a %.

**Comment by ArjamaM** [comment]
'In case you want to calculate the time-map for walking or cycling, you can set the average speed value to:

• Walking: 5 km/hr
• Cycling: 12 km/hr'

The new text to be added was this based on a jour fixe last month:

Motorways: 80
Trunk and primary: 60
Secondary roads: 50
Tertiary roads: 50
Connecting roads: 50
Service and track roads: 50
Residential roads: 40
Living_streets: 15
Footways: 5

**Comment by JowieXiang** [comment]
Checking how much effort is needed to add walk/cycling option to the calculate time map module

**Comment by janbehrens** [comment]
grass/variables/defaults/highway_types
```
highway="motorway" OR highway="motorway_link"
highway="trunk" OR highway="trunk_link" OR highway="primary" OR highway="primary_link"
highway="secondary" OR highway="secondary_link"
highway="tertiary" OR highway="tertiary_link"
highway="unclassified"
highway="service" OR highway="track"
highway="residential"
highway="living_street" OR highway="pedestrian"
highway="footway" OR highway="bridleway" OR highway="steps" OR highway="path"
```

**Comment by janbehrens** [comment]
grass/variables/defaults/roads_speed_defaults
```
Motorways: 80
Trunk and primary: 60
Secondary roads: 50
Tertiary roads: 50
Connecting roads: 50
Service and track roads: 50
Residential roads: 40
Living_streets: 15
Footways: 5
```
