### ISSUE TITLE
Bug: Results on map

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#85]
1. Results show up in the PDF but not in the map.
2. In some cases the results show, but only from the first query trial and not the later ones.

**Comment by janbehrens** [comment]
Need clarification! Which results are affected and how to reproduce the issue?

**Comment by ArjamaM** [comment]
Hi,

Added comments to it.

Quoting Jan Behrens <notifications@github.com>:

>  
>
>   Need clarification! Which results are affected and how to  
> reproduce the issue?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Links:
------
[1]  
https://github.com/citysciencelab/open-city-toolkit/issues/85#issuecomment-710021603
[2]
