### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#86]
After finishing a calculation, the user may want to refresh and start from scratch. By scratch meaning, not redefining location, adding map and so on but to re-draw a different polygon, points and so on. What should the user do in this case? Refresh the browser or run the module again or?

**Comment by janbehrens** [comment]
Please elaborate. In which situations is a refresh button needed?

**Comment by ArjamaM** [comment]
Comment added. It seems the comments did not get added first, I was  
changing them while in a meeting with Lisa so probably it was missing.

Quoting Jan Behrens <notifications@github.com>:

>  
>
>   Please elaborate. In which situations is a refresh button needed?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Links:
------
[1]  
https://github.com/citysciencelab/open-city-toolkit/issues/86#issuecomment-710017533
[2]

**Comment by janbehrens** [comment]
> After finishing a calculation, the user may want to refresh and start from scratch. By scratch meaning, not redefining location, adding map and so on but to re-draw a different polygon, points and so on. What should the user do in this case? Refresh the browser or run the module again or?

In this case the user can simply run the same module again (or any other).
