### ISSUE TITLE
Naming issue: "set location" to "add basemap", "add map" to "add layer"

### ISSUE THREAD

**Issue by JowieXiang** [citysciencelab/open-city-toolkit#96]

**Comment by janbehrens** [comment]
I'd prefer "Set basemap", because you set it only once in a while and you can't have multiple either.

**Comment by JowieXiang** [comment]
> I'd prefer "Set basemap", because you set it only once in a while and you can't have multiple either.

Ahh yes! It should be 'Set basemap' - I must have been dozing off...
